buildscript {
    repositories {
        mavenCentral()
        jcenter()
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
    }
}

allprojects {
    apply plugin: 'idea'
}

configure(subprojects) {
    apply plugin: 'java'
    sourceCompatibility = 1.8
}

subprojects {
    version = '0.1.0'
    ext.appName = 'libgdx-sandbox'
    repositories {
        mavenCentral()
        jcenter()
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
    }
}
