[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'

sourceSets.main.java.srcDirs = [ "src/" ]

dependencies {
    compile "com.badlogicgames.gdx:gdx:$gdxVersion"
    compile "com.badlogicgames.gdx:gdx-ai:$aiVersion"
    compile "com.badlogicgames.gdx:gdx-box2d:$gdxVersion"
    compile "com.badlogicgames.gdx:gdx-freetype:$gdxVersion"
    compile "com.badlogicgames.ashley:ashley:$ashleyVersion"
    compile "com.badlogicgames.gdx:gdx-controllers:$gdxVersion"
    compile "com.strongjoshua:libgdx-inGameConsole:$inGameConsoleVersion"
    compile "net.dermetfan.libgdx-utils:libgdx-utils-box2d:$utilsBox2dVersion"
    compile "com.github.czyzby:gdx-kiwi:$kiwiVersion.$gdxVersion"

    compile fileTree(dir: '../libs', include: '*.jar')
}
