[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'

sourceSets.main.java.srcDirs = [ "src/" ]

dependencies {
    api "com.badlogicgames.gdx:gdx:$gdxVersion"
    api "com.badlogicgames.gdx:gdx-ai:$aiVersion"
    api "com.badlogicgames.gdx:gdx-box2d:$gdxVersion"
    api "com.badlogicgames.gdx:gdx-freetype:$gdxVersion"
    api "com.badlogicgames.ashley:ashley:$ashleyVersion"
    api "com.badlogicgames.gdx:gdx-controllers:$gdxVersion"
    api "com.strongjoshua:libgdx-inGameConsole:$inGameConsoleVersion"
    api "net.dermetfan.libgdx-utils:libgdx-utils-box2d:$utilsBox2dVersion"

    api fileTree(dir: '../libs', include: '*.jar')
}
