apply plugin: 'application'

sourceSets.main.resources.srcDirs += [ rootProject.file('assets').absolutePath ]
sourceSets.main.java.srcDirs = [ "src/" ]
mainClassName = 'com.austinauts.libgdx.desktop.DesktopLauncher'
sourceCompatibility = 1.8

dependencies {
    implementation project(':core')
    implementation "com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdxVersion"
    implementation "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
    implementation "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-desktop"
    implementation "com.badlogicgames.gdx:gdx-freetype-platform:$gdxVersion:natives-desktop"
    implementation "com.badlogicgames.gdx:gdx-controllers-lwjgl3:$gdxVersion"
}

jar {
    archiveName "${appName}-${version}.jar"
    from { configurations.compile.collect { zipTree(it) } }
    manifest {
        attributes 'Main-Class': project.mainClassName
    }
}
